version: "3.8"
services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: universityapp
      MYSQL_USER: yavuz
      MYSQL_PASSWORD: yavuz
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./server
    container_name: node_server
    restart: always
    environment:
      DB_HOST: mysql
      DB_USER: yavuz
      DB_PASSWORD: yavuz
      DB_NAME: universityapp
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app # Kodu container içine bağla
      - /app/node_modules # node_modules'ü hariç tut (ÖNEMLİ!)
    depends_on:
      - mysql

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql_data:
